### PR TITLE
Halftime show improvement

### PR DESCRIPTION
**Pull request by RigglePrime**
mmmm myes fish

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
Please no linter cry
> [warn] Code style issues found in the above file(s). Forgot to run Prettier?

**Comment by RigglePrime** [comment]
Should be fixed now

**Comment by RigglePrime** [comment]
Whoops, wrong button

**Comment by Wayland-Smithy** [comment]
Github devs be like "humm yes let's put a major action button next to *post comment*"

**Pull request merged**
